### PR TITLE
Angular pt 2

### PR DESCRIPTION
**Pull request by lolptdr**
Please push what we have, contains updated code for showing teacher and student view for question sets and passing tests. Please keep branch as-is once merge is complete.

### CODE REVIEW

**Comment by allizad** [comment]
Closes #132 
And closes add-chart issue (not added)

**Comment by allizad** [comment]
Ran test on local machine and it passed :)

screen shot 2014-09-19 at 2 24 19 pm

**Comment by gilbert** [comment]
I will rerun the build

**Comment by gilbert** [comment]
Still failing

**Comment by allizad** [comment]
Passing on my machine:

screen shot 2014-09-19 at 2 28 19 pm

**Comment by gilbert** [comment]
Related to #177

**Pull request merged**
